parameters:
  webhooks_formats:
    raw: 'WEBHOOKS_FORMAT_RAW'
    activitypub: 'WEBHOOKS_FORMAT_ACTIVITYPUB'
    mattermost: 'WEBHOOKS_FORMAT_MATTERMOST'
    slack: 'WEBHOOKS_FORMAT_SLACK'
    yeswiki: 'WEBHOOKS_FORMAT_YESWIKI'
  webhooks_activitypub_default_actor: '' # If no actor field is defined semantically, this value will be used
  webhooks_activitypub_actors_base_url: '' # If an actor is defined, we can override the base URL with this config
  # Bot config (works for Mattermost if username and profile picture override is enabled)
  # See https://docs.mattermost.com/developer/webhooks-incoming.html
  webhooks_bot_name: 'YesWiki Bot'
  webhooks_bot_icon: '%base_url%tools/webhooks/presentation/images/default-bot.png'

services:
  _defaults:
    autowire: true
    public: true

  # Allows to use controllers as services
  YesWiki\Webhooks\Controller\:
    resource: 'controllers/*'
